# TCL File Generated by Component Editor 18.0
# Thu May 07 14:23:24 MDT 2020
# DO NOT MODIFY


# 
# jtag_mm1 "jtag_mm1" v1.0
#  2020.05.07.14:23:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module jtag_mm1
# 
set_module_property DESCRIPTION ""
set_module_property NAME jtag_mm1
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME jtag_mm1
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

